// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://example.com/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.example.com/support",
            "email": "support@example.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/activities": {
            "get": {
                "responses": {}
            },
            "post": {
                "responses": {}
            }
        },
        "/activities/alerts": {
            "get": {
                "responses": {}
            }
        },
        "/activities/summary/{userID}": {
            "get": {
                "responses": {}
            }
        },
        "/api/lab-samples": {
            "post": {
                "responses": {}
            }
        },
        "/api/lab-samples/{id}": {
            "get": {
                "responses": {}
            },
            "put": {
                "responses": {}
            },
            "delete": {
                "responses": {}
            }
        },
        "/api/lab-samples/{sample_id}/ucs-results": {
            "get": {
                "responses": {}
            }
        },
        "/api/lithology-logs": {
            "post": {
                "responses": {}
            }
        },
        "/api/lithology-logs/{id}": {
            "get": {
                "responses": {}
            },
            "put": {
                "responses": {}
            },
            "delete": {
                "responses": {}
            }
        },
        "/api/projects": {
            "get": {
                "responses": {}
            },
            "post": {
                "responses": {}
            }
        },
        "/api/projects/{id}": {
            "get": {
                "responses": {}
            },
            "put": {
                "responses": {}
            },
            "delete": {
                "responses": {}
            }
        },
        "/api/projects/{id}/stations": {
            "get": {
                "responses": {}
            }
        },
        "/api/projects/{project_id}/stations": {
            "get": {
                "responses": {}
            }
        },
        "/api/reports/project/{project_id}": {
            "get": {
                "responses": {}
            }
        },
        "/api/stations": {
            "post": {
                "responses": {}
            }
        },
        "/api/stations/{id}": {
            "get": {
                "responses": {}
            },
            "put": {
                "responses": {}
            },
            "delete": {
                "responses": {}
            }
        },
        "/api/stations/{station_id}/lab-samples": {
            "get": {
                "responses": {}
            }
        },
        "/api/stations/{station_id}/lithology-logs": {
            "get": {
                "responses": {}
            }
        },
        "/api/stations/{station_id}/lithology-logs/by-depth": {
            "get": {
                "responses": {}
            }
        },
        "/api/ucs-results": {
            "post": {
                "responses": {}
            }
        },
        "/api/ucs-results/{id}": {
            "get": {
                "responses": {}
            },
            "put": {
                "responses": {}
            },
            "delete": {
                "responses": {}
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{"http"},
	Title:            "Borehole Data Management API",
	Description:      "This is the Borehole Data Management API documentation.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
